export class FiltersItemDropdown {
  public isFromExportExcel: boolean;
  public isForSale: boolean;
  public isForPurchase: boolean;
  public idTiers: Array<number>;
  public idWarehouse: number;
  public idNature: number;
  public valueToSearch: string;
  public skip: number;
  public take: number;
  public idItemToIgnore: number;
  public isAvailableInStock: boolean;
  public isCentralOnly: boolean;
  public fromEcommerce: boolean;
  public isEcommerceOrNotOnly?: boolean;
  public isSelectOrDeselectAllEcommerce: boolean;
  public ignoreCharges: boolean;
  public idVehicleBrand: number;
  public idModel: number;
  public idSubModel: number;
  public tierSearch: string;
  public referenceSearch: string;
  public barCodeSearch: string;
  public designationSearch: string;
  public isWharehouseFilterRequired: boolean;
  public isForItemReplacement: boolean;
  // public like: boolean;
  public constaines: boolean;
  public isRestaurn = false;
  public isOnlyStockManaged: boolean;
  public minUnitHtSalesPrice: number;
  public maxUnitHtSalesPrice: number;
  public isForReappro: boolean;
  public idStorage: number;
  public id: number;
  public hasTiers: boolean;
  public idSalesPrice: number ;
  public idCustomer: number ;
  public idItemToCharge : Array<number>;
  public isAdvancePaymentNature: boolean;
  public isSubFinal: boolean;
  public isOnlyProductNature: boolean;
}
