export class LoginConst {
  public static LANGUAGE = 'language';
  public static ID_USER = 'IdUser';
  public static USER = 'user';
  public static OPERATION = 'op';
  public static REPLACE = 'replace';
  public static PATH = 'path';
  public static LANG_PATH = '/Lang';
  public static VALUE = 'value';
  public static EN = 'en';
  public static EMAIL = 'Email';
  public static PASSWORD = 'Password';
  public static CODE_COMPANY = 'CodeCompany';
  public static REQUIRED_COMPANY = 'REQUIRED_COMPANY';
  public static readonly CHANGE_DATA_BASE_CONNECTION = 'changeDataBaseConnection';
  public static REQUIRED_EMAIL_AND_PASSWORD = 'REQUIRED_EMAIL_AND_PASSWORD';
  public static WRONG_LOGIN_OR_PASSWORD = 'WRONG_LOGIN_OR_PASSWORD';
  public static  WRONG_PASSWORD   = 'WRONG_PASSWORD'
  public static WRONG_EMAIL = 'WRONG_EMAIL';
  public static AUTHENTICATE = 'authenticate';
  public static SET_DOT_NET_SESSION_INFORMATION = 'setDotNetSessionInformation';
  public static CHANGE_COMPANY = 'changeCompany';
  public static THIS_ACCOUNT_HAS_A_PROBLEM = 'THIS_ACCOUNT_HAS_A_PROBLEM';
  public static BAD_CREDENTIALS = 'Bad credentials';
  public static RETRIEVE_TOKEN = 'token/retrieve-token';
  public static RETRIEVE_TOKEN_USING_REFRESH_TOKEN = 'token/retrieve-token-using-refresh-token';
  public static REVOKE_TOKEN = 'token/revoke-token';
  public static MISSING_PERMISSIONS = 'MISSING_PERMISSIONS';
  public static GET_CURRENT_LANGUAGE = 'getCurrentLanguage';
  public static GET_CONNECTED_USER_LANGUAGE = 'user-language';
  public static CHANGE_CONNECTED_USER_LANGUAGE = 'change-user-language';
}
