
export class RoleConfigConstant {
  public static DashboardConfig = 'DASHBOARD';
  public static ModulesConfig = 'MODULES';
  public static StockConfig = 'STOCK';
  public static ItemListConfig = 'LISTEARTICLE_CONFIG';
  public static BillingSessionConfig = 'SESSION DE FACTURATION';
  public static ProjectConfig = 'CONTRAT_PRESTATION';
  public static SalesConfig = 'VENTES';
  public static PurchaseConfig = 'ACHATS';
  public static SettingsConfig = 'REGLAGES';
  public static PayConfig = 'PAIE';
  public static ImmobConfig = 'IMMOB';
  public static HelpdeskConfig = 'ASSISTANCE';
  public static ReportingConfig = 'REPORTING';
  public static CounterSalesConfig = 'COUNTER_SALES';
  public static DocumentControlConfig = 'DOCUMENTCONTROL';
  public static TreasuryConfig = 'TREASURY';
  public static GarageConfig = 'GARAGE';
  public static AccountingConfig = 'COMPTABILITE';
  public static CRA = 'CRA';
  public static LEAVE = 'LEAVE_CONFIG';
  public static LEAVE_CONFIG = 'CONGÉ';
  public static EXPENSE_REPORT = 'EXPENSE_REPORT';
  public static DOCUMENT = 'DOCUMENT';
  public static DOCUMENTS = 'DOCUMENTS';
  public static EXPENSE_REPORT_ROLE = 'NOTES DE FRAIS';
  public static SHARED_DOCUMENT = 'SHARED_DOCUMENT';
  public static ACCOUNTING_READ_WRITE = 'ACCOUNTING_READ_WRITE_CONFIG';
  public static ACCOUNTING_READ = 'ACCOUNTING_READ_CONFIG';
  public static AccountingDocumentConfig = 'ACCOUNTING_DOCUMENT';
  public static AccountingReportingsConfig = 'ACCOUNTING_REPORTINGS';
  public static AccountingLetteringConfig = 'ACCOUNTING_LETTERING';
  public static AccountingReconciliationBankStatementconfig = 'ACCOUNTING_RECONCILIATION_BANK_STATEMENT';
  public static AccountingImmobilizationConfig = 'ACCOUNTING_IMMOBILIZATION';
  public static AccountingImportDocumentsConfig = 'ACCOUNTING_IMPORT_DOCUMENTS';
  public static CrmConfig = 'CRM';
  public static ManufacturingConfig = 'MANUFACTURING_CONFIG';
  public static AdminConfig = 'ADMIN';
  public static PAYROLL_READ_CONFIG ='PAYROLL_READ_CONFIG';
  public static PAYROLL_READ_WRITE_CONFIG ='PAYROLL_READ_WRITE_CONFIG';
  public static SuperAdminConfig = 'SUPERADMIN';
  public static ConsultantConfig = 'CONSULTANT';
  public static EmployeWriteRead = 'Employe_Write_Read';
  public static EmployeRead = 'Employe_Read';
  public static Organigramme_Config = 'ORGANIGRAMME_CONFIG';
  public static ManagerConfig = 'MANAGER';
  public static Resp_RhConfig = 'RESPONSABLE_RH';
  public static Skills_Matrix = 'SKILLS_MATRIX';
  public static Formations_Config = 'FORMATIONS_CONFIG';
  public static Annual_Interviews = 'ANNUAL_INTERVIEWS';
  public static Annual_Interviews_Role = 'ENTRETIENS ANNUELS';
  public static G_ADMINISTRATIVE_RW = 'G_ADMINISTRATIVE_RW';
  public static G_CAREER_RW = 'CAREER_MANAGEMENT_RW';
  public static RecrutementRequestConfig = 'RECRUTEMENT_REQUEST';
  public static Resp_PayConfig = 'RESPONSABLE_PAY';
  public static PurchasePrice_HistoryConfig = 'PURCHASEPRICEHISTORY';
  public static EcommerceConfig = 'ECOMMERCE_CONFIG';
  public static EcommerceItemConfig = 'ECOMMERCEITEM';
  public static EcommerceTiersConfig = 'ECOMMERCETIERS';
  public static EcommerceMovementConfig = 'ECOMMERCEMOVEMENT';
  public static NotControlledConfig = 'NOTCONTROLLED';
  public static AllowAnonymousConfig = 'ALLOWANONYMOUS';
  public static SalesSettings = 'SALES_SETTINGS';
  public static PurchaseSettings = 'PURCHASE_SETTINGS';
  public static StockSettings = 'STOCK_SETTINGS';
  public static B2BSettings = 'B2B_SETTINGS';
  public static AccountingSettings = 'ACCOUNTING_SETTINGS';
  public static EcommerceSettings = 'ECOMMERCE_SETTINGS';
  public static InventoryConfig = 'INVENTORY_CONFIG';
  public static SalarySettings = 'SALARY_SETTINGS';
  public static PayrollSettings   = 'PAYROLL_SETTINGS';
  public static CRMSettings = 'CRM_SETTINGS' ;
  public static MANUFACTURING_SETTINGS = 'MANUFACTURING_SETTINGS' ;
  public static HRSettings = 'HR_SETTINGS' ;
  public static SettingContractType = 'SETTING_CONTRACT_TYPE';
  public static UserManagement = 'USER_MANAGEMENT' ;
  public static Starkdrive = 'STARKDRIVE';
  public static MailingSettings = 'MAILING_SETTINGS';
  public static SALESDELIVERYFORM = 'BL_CONFIG';
  public static SALESINVOICECONFIG = 'FACTURE_CONFIG';
  public static SALESASSETCONFIG = 'AVOIR_CONFIG';
  public static SALESINVOICEASSETCONFIG = 'SALESINVOICEASSET_CONFIG';
  public static SALESFINANCIALASSETCONFIG = 'SALESFINANCIALASSET_CONFIG';
  public static ItemPrice_Update = 'ITEMPRICE_SAUPDATE_CONFIG' ;
  public static COMMANDECONFIG = 'COMMANDE_CONFIG';
  public static DEVIS = 'DEVISCONFIG' ;
  public static CLIENTCONFIG = 'CLIENT_CONFIG' ;
  public static SEARCHITEMCONFIG = 'SEARCHITEM_CONFIG' ;
  public static DahsboardModule = 'DASHBOARD';
  public static ModulesModule = 'MODULES';
  public static StockModule = 'STOCK';
  public static ItemListModule = 'ARTICLE';
  public static BillingSessionModule = 'SESSION DE FACTURATION';
  public static ProjectModule = 'CONTRAT DE PRESTATION';
  public static SalesModule = 'VENTES';
  public static RhModule = 'RH';
  public static Employee_RW_Config ='EMPLOYE_WRITE_READ';
  public static PAIE_READ_WRITE ='Payroll_read_write_config';
  public static RecrutementRequest = 'RECRUTEMENT_REQUEST';
  public static RecrutementOffer = 'RECRUTEMENT_OFFER';
  public static Candidates = 'CANDIDATES';
  public static RecruitmentConfig = 'RECRUITMENT_CONFIG';
  public static PurchaseModule = 'ACHAT';
  public static SettingsModule = 'REGLAGES';
  public static PayModule = 'PAIE';
  public static ImmobModule = 'IMMOBILISATION';
  public static HelpdeskModule = 'ASSISTANCE';
  public static ReportingModule = 'REPORTING';
  public static DocumentControlModule = 'DOCUMENTCONTROL';
  public static TreasuryModule = 'TREASURY';
  public static AccountingModule = 'ACCOUNTING';
  public static CrmModule = 'CRM';
  public static ManufacturingModule = 'MANUFACTURING';
  public static AdminModule = 'ADMIN';
  public static SuperAdminModule = 'SUPERADMIN';
  public static ConsultantModule = 'CONSULTANT';
  public static ManagerModule = 'MANAGER';
  public static Resp_RhModule = 'RESP_RH';
  public static Resp_PayModule = 'RESP_PAY';
  public static PurchasePrice_HistoryModule = 'PURCHASEPRICEHISTORY';
  public static EcommerceModule = 'ECOMMERCE';
  public static EcommerceItemModule = 'ECOMMERCEITEM';
  public static EcommerceTiersModule = 'ECOMMERCETIERS';
  public static EcommerceMovementModule = 'ECOMMERCEMOVEMENT';
  public static NotControlledModule = 'NOTCONTROLLED';
  public static AllowAnonymousModule = 'ALLOWANONYMOUS';
  public static StockCorrectionConfig = 'STOCKCORRECTION';
  public static StockCorrectionModule = 'STOCKCORRECTION';
  public static OfConfirmationInvoice = 'OF-CONFIRMATION-INVOICE';
  public static PasswordSettings = 'PASSWORD_SETTINGS';
  public static Manufacturingsettings = 'MANUFACTURING_SETTINGS';
  public static FABRICATIONCONFIG = 'FABRICATION_CONFIG';
  public static TASKCONFIG = 'TASK_CONFIG';
  public static TIMELINECONFIG = 'TIMELINE_CONFIG';
  public static CALANDERCONFIG = 'CALANDER_CONFIG';
  public static LOANADVANCECONFIG = 'LOANADVANCE_CONFIG';
  public static SUPPLIERCONFIG = 'SUPPLIER_CONFIG';
  public static PURCHASEINVOICECONFIG = 'PURCHASEINVOICE_CONFIG';
  public static PURCHASEORDERCONFIG = 'PURCHASEORDER_CONFIG';
  public static OEMCONFIG = 'OEM_CONFIG';
  public static MOVEMENTHISTORYCONFIG = 'MOVEMENT-HISTORY_CONFIG';
  public static PRIVILEGESCONFIG = 'PRIVILEGES_CONFIG';
  public static DELTEDOCLINEPUCONFIG = 'DELETEDOCUMENTLINEPURCHASE_CONFIG';
  public static DELETEMULTIPLEDOCLINESPU_CONFIG = 'DELETEMULTIPLEDOCUMENTLINESPURCHASE_CONFIG';
  public static DELETEDOCLINESACONFIG = 'DELETEDOCUMENTLINE_CONFIG';
  public static DELETEMULTIPLEDOCLINESSACONFIG = 'DELETEMULTIPLEDOCUMENTLINESSALE_CONFIG'  ;
  public static DELETEDOCUMENTSALESCONFIG = 'DELETE_DOCUMENT_SALES';
  public static DELETEDOCUMENTSTOCKCONFIG = 'DELETE_DOCUMENT_STOCK';
  public static DELETEDOCUMENTPURCHASECONFIG = 'DELETE_DOCUMENT_PURCHASE';
  public static PURCHASEITEMCONFIG = 'PURCHASEITEM_CONFIG';
  public static PAYSLIPHISTORYCONFIG = 'PAYROLLHISTORY_CONFIG';
  public static PAYSLIPHISTORY = 'HISTORIQUE DE PAIE';
  public static CNSSDECLARATIONCONFIG = 'DECLARATION_CNSS';
  public static TRANSFER_ORDER = 'ORDRE_VIREMENT';
  public static ORDER_TRANSFER = 'ORDRE DE VIREMENT';
  public static ACCOUNTING = 'COMPTABILITE' ;
  public static CRM = 'CRM' ;
  public static CANCELORDER = 'CANCEL_ORDER' ;
  public static CURRENCY = 'CURRENCY';
  public static PRICES = 'PRICES';
  public static RETENUE_SOURCE = 'RETENUE_SOURCE';
  public static DECLARATION_EMPLOYEE ='DECLARATION_EMPLOYEE';
  public static IMPORTDOCUMENT_SA = 'IMPORT_DOCUMENT_SA';
  public static IMPORTDOCUMENT_PU = 'IMPORT_DOCUMENT';
  public static CLIENTTREASURY = 'CLIENT_TREASURY' ;
  public static TIERTREASURY = 'TIER_TREASURY' ;
  public static CASHREGISTERTREASURY = 'CASH_REGISTER_TREASURY' ;
  public static BANKTREASURY = 'BANK_TREASURY' ;
  public static OUTSTANDINGCLIENT = 'OUTSTANDING_CLIENT_TREASURY';
  public static OUTSTANDINGTIER = 'OUTSTANDING_TIER_TREASURY';
  public static VALIDATESTOCKMOVEMENT = 'VALIDATE_STOCK_MOVEMENT' ;
  public static TRANSFERSTOCKMOVEMENT = 'TRANSFER_STOCK_MOVEMENT' ;
  public static RECEIVESTOCKMOVEMENT = 'RECEIVE_STOCK_MOVEMENT' ;
  public static CONTRACT_FULL = 'CONTRAT-FULL' ;
  public static CONTRACT_DISABLED_ALL_DATA = 'CONTRACT-DISABLED-ALL-DATA' ;
  public static Contract_DISABLED_WITHOUT_BASESALARY_BONUS = 'CONTRACT-DISABLED-WITHOUT-BASESALARY-BONUS' ;
  public static GESTION_GARAGE = 'GESTION_GARAGE';
  public static GARAGE_CONFIG = 'GARAGE_CONFIG';
  public static SESSION_PAIE = "SESSION_PAIE";
  public static PURCHASE_RESPONSIBLE = 'PURCHASERESPONSABLE_CONFIG';
  public static TREASURY_SETTINGS ='TREASURY_SETTINGS';
  public static TERM_BILLING = 'TERMBILLING-CONFIG';
  public static UPDATE_PRICE_SA='UPDATEPRICE_SA';
  public static UPDATE_PRICE_PU='UPDATEPRICE_PU';
  public static UPDATE_DISCOUNT_SA='UPDATEDISCOUNT_SA';
  public static UPDATE_DISCOUNT_PU='UPDATEDISCOUNT_PU';
  public static RECEIVALBES_STATE_CLIENT = 'RECEIVABLESSTATE-CLIENT';
  public static RECEIVALBES_STATE_FRS = 'RECEIVABLESSTATE-FRS';
  public static SHELF_STORAGE = 'SHELFSTORAGE-CONFIG';
  public static STOCK_VALUATION ='STOCKVALUATION_CONFIG';
  public static TIER_EXTRACT ='TIEREXTRACT_CONFIG';
  public static VAT_DECLARARION='VATDECLARATION_CONFIG';
  public static DOCUMENT_CONTROL='DOCUMENTCONTROL_CONFIG';
  public static USER_SETTINGS ='USERSETTINGS';
  public static USER_GROUP_SETTINGS ='USERGROUPSETTINGS';
  public static ROLE_SETTINGS = 'ROLESETTINGS';
  public static Exit_employee_config = 'EXIT_EMPLOYEE';


  public static LIST_STRING = 'LIST-';
  public static ADD_STRING = 'ADD-';
  public static UPDATE_STRING = 'UPDATE-';
  public static DELETE_STRING = 'DELETE-';
  public static SHOW_STRING = 'SHOW-';
  public static PRINT_STRING = 'PRINT-';

  public static DocumentLineNegotiationOptions = 'UPDATE-DOCUMENTLINENEGOTIATIONOPTIONS';

  public static LIST = {
    ITEM: 'LIST-ITEM',
    WAREHOUSE: 'LIST-WAREHOUSE',
    INVENTORYMOVEMENT: 'LIST-INVENTORYMOVEMENT',
    TRANSFERTMOVEMENT: 'LIST-TRANSFERTMOVEMENT',
    TRANSFERMOVEMENT: 'LIST-TRANSFERMOVEMENT',
    SUPPLIER: 'LIST-SUPPLIER',
    PURCHASEORDER: 'LIST-PURCHASEORDER',
    PURCHASEFINALORDER: 'LIST-PURCHASEFINALORDER',
    PURCHASEDELIVERY: 'LIST-PURCHASEDELIVERY',
    PURCHASEINVOICE: 'LIST-PURCHASEINVOICE',
    PURCHASEASSET: 'LIST-PURCHASEASSET',
    CLAIMS: 'LIST-CLAIMS',
    PURCHASEREQUEST: 'LIST-PURCHASEREQUEST',
    PRICEREQUEST: 'LIST-PRICEREQUEST',
    PROJECT: 'LIST-PROJECT',
    CUSTOMER: 'LIST-CUSTOMER',
    SALESORDER: 'LIST-SALESORDER',
    SALESFINALORDER: 'LIST-SALESFINALORDER',
    SALESDELIVERY: 'LIST-SALESDELIVERY',
    SALESINVOICE: 'LIST-SALESINVOICE',
    SALESINVOICEASSET: 'LIST-SALESINVOICEASSET',
    SALESASSET: 'LIST-SALESASSET',
    SALESQUOTATION: 'LIST-SALESQUOTATION',
    PRICE: 'LIST-PRICES',
    ORDERPROJECT: 'LIST-ORDERPROJECT',
    ACTIVE: 'LIST-ACTIVE',
    BE: 'LIST-BE',
    BS: 'LIST-BS',
    SEARCHITEM: 'LIST-SEARCHITEM',
    PURCHASEDELIVERY_SA: 'LIST-PURCHASEDELIVERY_SA',
    PURCHASEPRICEHISTORY: 'LIST-PURCHASEPRICEHISTORY',
    PURCHASEDELIVERYPRICE_SA: 'LIST-PURCHASEDELIVERYPRICE_SA',
    TREASURY: 'LIST-TREASURY',
    DOCUMENTCONTROL: 'LIST-DOCUMENTCONTROL',
    ITEMPURCHASE: 'LIST-ITEMPURCHASE',
    PURCHASEBALANCE: 'PURCHASEBALANCE',
    EMPLOYEE: 'LIST-EMPLOYEE',
    TEAM: 'LIST-TEAM',
    CONTRACT: 'LIST-Contract',
    SESSION: 'LIST-SESSION',
    TRANSFERORDER: 'LIST-TRANSFERORDER',
    CNSSDECLARATION: 'LIST-CNSSDECLARATION',
    SOURCEDEDUCTIONSESSION: 'LIST-SOURCEDEDUCTIONSESSION',
    EMPLOYERDECLARATION: 'LIST-EMPLOYERDECLARATION',
    LOAN: 'LIST-LOAN',
    BALANCED_LINE: 'LIST-BALANCED_LINE',
    PERIOD: 'LIST-PERIOD'
  };

  public static ADD = {
    ITEM: 'ADD-ITEM',
    WAREHOUSE: 'ADD-WAREHOUSE',
    INVENTORYMOVEMENT: 'ADD-INVENTORYMOVEMENT',
    TRANSFERTMOVEMENT: 'ADD-TRANSFERTMOVEMENT',
    TRANSFERMOVEMENT: 'ADD-TRANSFERMOVEMENT',
    SUPPLIER: 'ADD-SUPPLIER',
    PURCHASEORDER: 'ADD-PURCHASEORDER',
    PURCHASEFINALORDER: 'ADD-PURCHASEFINALORDER',
    PURCHASEDELIVERY: 'ADD-PURCHASEDELIVERY',
    PURCHASEINVOICE: 'ADD-PURCHASEINVOICE',
    PURCHASEASSET: 'ADD-PURCHASEASSET',
    CLAIMS: 'ADD-CLAIMS',
    PURCHASEREQUEST: 'ADD-PURCHASEREQUEST',
    PRICEREQUEST: 'ADD-PRICEREQUEST',
    PROJECT: 'ADD-PROJECT',
    CUSTOMER: 'ADD-CUSTOMER',
    SALESORDER: 'ADD-SALESORDER',
    SALESFINALORDER: 'ADD-SALESFINALORDER',
    SALESDELIVERY: 'ADD-SALESDELIVERY',
    SALESINVOICE: 'ADD-SALESINVOICE',
    SALESINVOICEASSET: 'ADD-SALESINVOICEASSET',
    SALESASSET: 'ADD-SALESASSET',
    SALESQUOTATION: 'ADD-SALESQUOTATION',
    PRICE: 'ADD-PRICE',
    ORDERPROJECT: 'ADD-ORDERPROJECT',
    ACTIVE: 'ADD-ACTIVE',
    BE: 'ADD-BE',
    BS: 'ADD-BS',
    SEARCHITEM: 'ADD-SEARCHITEM',
    PURCHASEDELIVERY_SA: 'ADD-PURCHASEDELIVERY_SA',
    PURCHASEORDER_SA: 'ADD-PURCHASEORDER_SA',
    PURCHASEQUOTATION_SA: 'ADD-PURCHASEQUOTATION_SA',
    PURCHASEINVOICE_SA: 'ADD-PURCHASEINVOICE_SA',
    PURCHASEASSET_SA: 'ADD-PURCHASEASSET_SA',
    PURCHASEFINALORDER_SA: 'ADD-PURCHASEFINALORDER_SA',
    SALESORDER_SA: 'ADD-SALESORDER',
    SALESFINALORDER_SA: 'ADD-SALESFINALORDER_SA',
    SALESDELIVERY_SA: 'ADD-SALESDELIVERY_SA',
    SALESINVOICE_SA: 'ADD-SALESINVOICE_SA',
    SALESINVOICEASSET_SA: 'ADD-SALESINVOICEASSET_SA',
    SALESASSET_SA: 'ADD-SALESASSET_SA',
    SALESQUOTATION_SA: 'ADD-SALESQUOTATION_SA',
    TREASURY: 'ADD-TREASURY',
    DOCUMENTCONTROL: 'ADD-DOCUMENTCONTROL',
    EMPLOYEE: 'ADD-EMPLOYEE',
    CONTRACT: 'ADD-Contract',
    TEAM: 'ADD-TEAM',
    SESSION: 'ADD-SESSION',
    TRANSFERORDER: 'ADD-TRANSFERORDER',
    CNSSDECLARATION: 'ADD-CNSSDECLARATION',
    SOURCEDEDUCTIONSESSION: 'ADD-SOURCEDEDUCTIONSESSION',
    EMPLOYERDECLARATION: 'ADD-EMPLOYERDECLARATION',
    BALANCED_LINE: 'ADD-BALANCED_LINE',
    PERIOD: 'ADD-PERIOD'
  };

  public static UPDATE = {
    ITEM: 'UPDATE-ITEM',
    WAREHOUSE: 'UPDATE-WAREHOUSE',
    INVENTORYMOVEMENT: 'UPDATE-INVENTORYMOVEMENT',
    TRANSFERTMOVEMENT: 'UPDATE-TRANSFERTMOVEMENT',
    TRANSFERMOVEMENT: 'UPDATE-TRANSFERMOVEMENT',
    SUPPLIER: 'UPDATE-SUPPLIER',
    PURCHASEORDER: 'UPDATE-PURCHASEORDER',
    PURCHASEFINALORDER: 'UPDATE-PURCHASEFINALORDER',
    PURCHASEDELIVERY: 'UPDATE-PURCHASEDELIVERY',
    PURCHASEINVOICE: 'UPDATE-PURCHASEINVOICE',
    PURCHASEASSET: 'UPDATE-PURCHASEASSET',
    CLAIMS: 'UPDATE-CLAIMS',
    PURCHASEREQUEST: 'UPDATE-PURCHASEREQUEST',
    PRICEREQUEST: 'UPDATE-PRICEREQUEST',
    PROJECT: 'UPDATE-PROJECT',
    CUSTOMER: 'UPDATE-CUSTOMER',
    SALESORDER: 'UPDATE-SALESORDER',
    SALESFINALORDER: 'UPDATE-SALESFINALORDER',
    SALESDELIVERY: 'UPDATE-SALESDELIVERY',
    SALESINVOICE: 'UPDATE-SALESINVOICE',
    SALESINVOICEASSET: 'UPDATE-SALESINVOICEASSET',
    SALESFINANCIALASSET: 'UPDATE-SALESFINANCIALASSET',
    SALESASSET: 'UPDATE-SALESASSET',
    SALESQUOTATION: 'UPDATE-SALESQUOTATION',
    PRICE: 'UPDATE-PRICES',
    ORDERPROJECT: 'UPDATE-ORDERPROJECT',
    ACTIVE: 'UPDATE-ACTIVE',
    BE: 'UPDATE-BE',
    BS: 'UPDATE-BS',
    SEARCHITEM: 'UPDATE-SEARCHITEM',
    PURCHASEDELIVERY_SA: 'UPDATE-PURCHASEDELIVERY_SA',
    PURCHASEORDER_SA: 'UPDATE-PURCHASEORDER_SA',
    PURCHASEQUOTATION_SA: 'UPDATE-PURCHASEQUOTATION_SA',
    PURCHASEINVOICE_SA: 'UPDATE-PURCHASEINVOICE_SA',
    PURCHASEASSET_SA: 'UPDATE-PURCHASEASSET_SA',
    PURCHASEFINALORDER_SA: 'UPDATE-PURCHASEFINALORDER_SA',
    SALESORDER_SA: 'UPDATE-SALESORDER_SA',
    SALESFINALORDER_SA: 'UPDATE-SALESFINALORDER_SA',
    SALESDELIVERY_SA: 'UPDATE-SALESDELIVERY_SA',
    SALESINVOICE_SA: 'UPDATE-SALESINVOICE_SA',
    SALESINVOICEASSET_SA: 'UPDATE-SALESINVOICEASSET_SA',
    SALESASSET_SA: 'UPDATE-SALESASSET_SA',
    SALESQUOTATION_SA: 'UPDATE-SALESQUOTATION_SA',
    BE_SA: 'UPDATE-BE_SA',
    BS_SA: 'UPDATE-BS_SA',
    TREASURY: 'UPDATE-TREASURY',
    DOCUMENTCONTROL: 'UPDATE-DOCUMENTCONTROL',
    RESERVEDDOCUMENTLINE_SA: 'UPDATE-RESERVEDDOCUMENTLINE_SA',
    EMPLOYEE: 'UPDATE-EMPLOYEE',
    CONTRACT: 'CONTRACT-UPDATE',
    SESSION: 'UPDATE-SESSION',
    TRANSFERORDER: 'UPDATE-TRANSFERORDER',
    CNSSDECLARATION: 'UPDATE-CNSSDECLARATION',
    SOURCEDEDUCTIONSESSION: 'UPDATE-SOURCEDEDUCTIONSESSION',
    EMPLOYERDECLARATION: 'UPDATE-EMPLOYERDECLARATION',
    BALANCED_LINE: 'UPDATE-BALANCED_LINE'
  };

  public static DELETE = {
    ITEM: 'DELETE-ITEM',
    WAREHOUSE: 'DELETE-WAREHOUSE',
    INVENTORYMOVEMENT: 'DELETE-INVENTORYMOVEMENT',
    TRANSFERTMOVEMENT: 'DELETE-TRANSFERTMOVEMENT',
    TRANSFERMOVEMENT: 'DELETE-TRANSFERMOVEMENT',
    SUPPLIER: 'DELETE-SUPPLIER',
    PURCHASEORDER: 'DELETE-PURCHASEORDER',
    PURCHASEFINALORDER: 'DELETE-PURCHASEFINALORDER',
    PURCHASEDELIVERY: 'DELETE-PURCHASEDELIVERY',
    PURCHASEINVOICE: 'DELETE-PURCHASEINVOICE',
    PURCHASEASSET: 'DELETE-PURCHASEASSET',
    CLAIMS: 'DELETE-CLAIMS',
    PURCHASEREQUEST: 'DELETE-PURCHASEREQUEST',
    PRICEREQUEST: 'DELETE-PRICEREQUEST',
    PROJECT: 'DELETE-PROJECT',
    CUSTOMER: 'DELETE-CUSTOMER',
    SALESORDER: 'DELETE-SALESORDER',
    SALESFINALORDER: 'DELETE-SALESFINALORDER',
    SALESDELIVERY: 'DELETE-SALESDELIVERY',
    SALESINVOICE: 'DELETE-SALESINVOICE',
    SALESINVOICEASSET: 'DELETE-SALESINVOICEASSET',
    SALESFINANCIALASSET: 'DELETE-SALESFINANCIALASSET',
    SALESASSET: 'DELETE-SALESASSET',
    SALESQUOTATION: 'DELETE-SALESQUOTATION',
    PRICE: 'DELETE-PRICE',
    ORDERPROJECT: 'DELETE-ORDERPROJECT',
    ACTIVE: 'DELETE-ACTIVE',
    BE: 'DELETE-BE',
    BS: 'DELETE-BS',
    SEARCHITEM: 'DELETE-SEARCHITEM',
    PURCHASEDELIVERY_SA: 'DELETE-PURCHASEDELIVERY_SA',
    PURCHASEORDER_SA: 'DELETE-PURCHASEORDER_SA',
    PURCHASEQUOTATION_SA: 'DELETE-PURCHASEQUOTATION_SA',
    PURCHASEINVOICE_SA: 'DELETE-PURCHASEINVOICE_SA',
    PURCHASEASSET_SA: 'DELETE-PURCHASEASSET_SA',
    PURCHASEFINALORDER_SA: 'DELETE-PURCHASEFINALORDER_SA',
    SALESORDER_SA: 'DELETE-SALESORDER_SA',
    SALESFINALORDER_SA: 'DELETE-SALESFINALORDER_SA',
    SALESDELIVERY_SA: 'DELETE-SALESDELIVERY_SA',
    SALESINVOICE_SA: 'DELETE-SALESINVOICE_SA',
    SALESINVOICEASSET_SA: 'DELETE-SALESINVOICEASSET_SA',
    SALESASSET_SA: 'DELETE-SALESASSET_SA',
    SALESQUOTATION_SA: 'DELETE-SALESQUOTATION_SA',
    BE_SA: 'DELETE-BE_SA',
    BS_SA: 'DELETE-BS_SA',
    TREASURY: 'DELETE-TREASURY',
    DOCUMENTCONTROL: 'DELETE-DOCUMENTCONTROL',
    DOCUMENTLINE_SA: 'DELETE-DOCUMENTLINE_SA',
    RESERVEDDOCUMENTLINE_SA: 'DELETE-RESERVEDDOCUMENTLINE_SA',
    MULTIPLEDOCUMENTLINES_SA: 'DELETE-MULTIPLEDOCUMENTLINES_SA',
    MULTIPLEDOCUMENTLINES_PU: 'DELETE-MULTIPLEDOCUMENTLINES_PU',
    DOCUMENTLINE_PU: 'DELETE-DOCUMENTLINE_PU',
    BALANCED_LINE: 'DELETE-BALANCED_LINE',
    EMPLOYEE: 'DELETE-EMPLOYEE',
    SESSION: 'DELETE-SESSION',
    TRANSFERORDER: 'DELETE-TRANSFERORDER',
    CNSSDECLARATION: 'DELETE-CNSSDECLARATION',
    SOURCEDEDUCTIONSESSION: 'DELETE-SOURCEDEDUCTIONSESSION',
    EMPLOYERDECLARATION: 'DELETE-EMPLOYERDECLARATION',
    DOCUMENT_PURCHASE: 'DELETE-DOCUMENT_PURCHASE',
    DOCUMENT_SALES: 'DELETE-DOCUMENT_SALES',
    DOCUMENT_STOCK: 'DELETE-DOCUMENT_STOCK',
  };

  public static SHOW = {
    ITEM: 'SHOW-ITEM',
    WAREHOUSE: 'SHOW-WAREHOUSE',
    INVENTORYMOVEMENT: 'SHOW-INVENTORYMOVEMENT',
    TRANSFERTMOVEMENT: 'SHOW-TRANSFERTMOVEMENT',
    TRANSFERMOVEMENT: 'SHOW-TRANSFERMOVEMENT',
    SUPPLIER: 'SHOW-SUPPLIER',
    PURCHASEORDER: 'SHOW-PURCHASEORDER',
    PURCHASEFINALORDER: 'SHOW-PURCHASEFINALORDER',
    PURCHASEDELIVERY: 'SHOW-PURCHASEDELIVERY',
    PURCHASEINVOICE: 'SHOW-PURCHASEINVOICE',
    PURCHASEASSET: 'SHOW-PURCHASEASSET',
    CLAIMS: 'SHOW-CLAIMS',
    PURCHASEREQUEST: 'SHOW-PURCHASEREQUEST',
    PRICEREQUEST: 'SHOW-PRICEREQUEST',
    PROJECT: 'SHOW-PROJECT',
    CUSTOMER: 'SHOW-CUSTOMER',
    SALESORDER: 'SHOW-SALESORDER',
    SALESFINALORDER: 'SHOW-SALESFINALORDER',
    SALESDELIVERY: 'SHOW-SALESDELIVERY',
    SALESINVOICE: 'SHOW-SALESINVOICE',
    SALESINVOICEASSET: 'SHOW-SALESINVOICEASSET',
    SALESASSET: 'SHOW-SALESASSET',
    SALESQUOTATION: 'SHOW-SALESQUOTATION',
    PRICE: 'SHOW-PRICE',
    ORDERPROJECT: 'SHOW-ORDERPROJECT',
    ACTIVE: 'SHOW-ACTIVE',
    BE: 'SHOW-BE',
    BS: 'SHOW-BS',
    SEARCHITEM: 'SHOW-SEARCHITEM',
    PURCHASEDELIVERY_SA: 'SHOW-PURCHASEDELIVERY_SA',
    PURCHASEORDER_SA: 'SHOW-PURCHASEORDER_SA',
    PURCHASEQUOTATION_SA: 'SHOW-PURCHASEQUOTATION_SA',
    PURCHASEINVOICE_SA: 'SHOW-PURCHASEINVOICE_SA',
    PURCHASEASSET_SA: 'SHOW-PURCHASEASSET_SA',
    PURCHASEFINALORDER_SA: 'SHOW-PURCHASEFINALORDER_SA',
    SALESORDER_SA: 'SHOW-SALESORDER_SA',
    SALESFINALORDER_SA: 'SHOW-SALESFINALORDER_SA',
    SALESDELIVERY_SA: 'SHOW-SALESDELIVERY_SA',
    SALESINVOICE_SA: 'SHOW-SALESINVOICE_SA',
    SALESINVOICEASSET_SA: 'SHOW-SALESINVOICEASSET_SA',
    SALESASSET_SA: 'SHOW-SALESASSET_SA',
    SALESQUOTATION_SA: 'SHOW-SALESQUOTATION_SA',
    TREASURY: 'SHOW-TREASURY',
    DOCUMENTCONTROL: 'SHOW-DOCUMENTCONTROL',
    BALANCED_LINE: 'SHOW-BALANCED_LINE',
    EMPLOYEE: 'SHOW-EMPLOYEE',
    SESSION: 'SHOW-SESSION',
    TRANSFERORDER: 'SHOW-TRANSFERORDER',
    CNSSDECLARATION: 'SHOW-CNSSDECLARATION',
    SOURCEDEDUCTIONSESSION: 'SHOW-SOURCEDEDUCTIONSESSION',
    EMPLOYERDECLARATION: 'SHOW-EMPLOYERDECLARATION'
  };

  public static PRINT = {
    ITEM: 'PRINT-ITEM',
    WAREHOUSE: 'PRINT-WAREHOUSE',
    INVENTORYMOVEMENT: 'PRINT-INVENTORYMOVEMENT',
    TRANSFERTMOVEMENT: 'PRINT-TRANSFERTMOVEMENT',
    TRANSFERMOVEMENT: 'PRINT-TRANSFERMOVEMENT',
    SUPPLIER: 'PRINT-SUPPLIER',
    PURCHASEORDER: 'PRINT-PURCHASEORDER',
    PURCHASEFINALORDER: 'PRINT-PURCHASEFINALORDER',
    PURCHASEDELIVERY: 'PRINT-PURCHASEDELIVERY',
    PURCHASEINVOICE: 'PRINT-PURCHASEINVOICE',
    PURCHASEASSET: 'PRINT-PURCHASEASSET',
    PURCHASEQUOTATION: 'PRINT-PURCHASEQUOTATION',
    CLAIMS: 'PRINT-CLAIMS',
    PURCHASEREQUEST: 'PRINT-PURCHASEREQUEST',
    PRICEREQUEST: 'PRINT-PRICEREQUEST',
    PROJECT: 'PRINT-PROJECT',
    CUSTOMER: 'PRINT-CUSTOMER',
    SALESORDER: 'PRINT-SALESORDER',
    SALESFINALORDER: 'PRINT-SALESFINALORDER',
    SALESDELIVERY: 'PRINT-SALESDELIVERY',
    SALESINVOICE: 'PRINT-SALESINVOICE',
    SALESINVOICEASSET: 'PRINT-SALESINVOICEASSET',
    SALESFINANCIALASSET: 'PRINT-SALESFINANCIALASSET',
    SALESASSET: 'PRINT-SALESASSET',
    SALESQUOTATION: 'PRINT-SALESQUOTATION',
    PRICE: 'PRINT-PRICE',
    ORDERPROJECT: 'PRINT-ORDERPROJECT',
    ACTIVE: 'PRINT-ACTIVE',
    BE: 'PRINT-BE',
    BS: 'PRINT-BS',
    SEARCHITEM: 'PRINT-SEARCHITEM',
    PURCHASEDELIVERY_SA: 'PRINT-PURCHASEDELIVERY_SA',
    PURCHASEORDER_SA: 'PRINT-PURCHASEORDER_SA',
    PURCHASEQUOTATION_SA: 'PRINT-PURCHASEQUOTATION_SA',
    PURCHASEINVOICE_SA: 'PRINT-PURCHASEINVOICE_SA',
    PURCHASEASSET_SA: 'PRINT-PURCHASEASSET_SA',
    PURCHASEFINALORDER_SA: 'PRINT-PURCHASEFINALORDER_SA',
    TREASURY: 'PRINT-TREASURY',
    DOCUMENTCONTROL: 'PRINT-DOCUMENTCONTROL',
    BALANCED_LINE: 'PRINT-BALANCED_LINE',
    EMPLOYEE: 'PRINT-EMPLOYEE',
    SESSION: 'PRINT-SESSION',
    TRANSFERORDER: 'PRINT-TRANSFERORDER',
    CNSSDECLARATION: 'PRINT-CNSSDECLARATION'
  };

  public static VALIDATE = {
    ITEM: 'VALIDATE-ITEM',
    WAREHOUSE: 'VALIDATE-WAREHOUSE',
    INVENTORYMOVEMENT: 'VALIDATE-INVENTORYMOVEMENT',
    TRANSFERTMOVEMENT: 'VALIDATE-TRANSFERTMOVEMENT',
    TRANSFERMOVEMENT: 'VALIDATE-TRANSFERMOVEMENT',
    SUPPLIER: 'VALIDATE-SUPPLIER',
    PURCHASEORDER: 'VALIDATE-PURCHASEORDER',
    PURCHASEFINALORDER: 'VALIDATE-PURCHASEFINALORDER',
    PURCHASEDELIVERY: 'VALIDATE-PURCHASEDELIVERY',
    PURCHASEINVOICE: 'VALIDATE-PURCHASEINVOICE',
    PURCHASEASSET: 'VALIDATE-PURCHASEASSET',
    CLAIMS: 'VALIDATE-CLAIMS',
    PURCHASEREQUEST: 'VALIDATE-PURCHASEREQUEST',
    PRICEREQUEST: 'VALIDATE-PRICEREQUEST',
    PROJECT: 'VALIDATE-PROJECT',
    CUSTOMER: 'VALIDATE-CUSTOMER',
    SALESORDER: 'VALIDATE-SALESORDER',
    SALESFINALORDER: 'VALIDATE-SALESFINALORDER',
    SALESDELIVERY: 'VALIDATE-SALESDELIVERY',
    SALESINVOICE: 'VALIDATE-SALESINVOICE',
    SALESINVOICEASSET: 'VALIDATE-SALESINVOICEASSET',
    SALESASSET: 'VALIDATE-SALESASSET',
    SALESQUOTATION: 'VALIDATE-SALESQUOTATION',
    PRICE: 'VALIDATE-PRICE',
    ORDERPROJECT: 'VALIDATE-ORDERPROJECT',
    ACTIVE: 'VALIDATE-ACTIVE',
    BE: 'VALIDATE-BE',
    BS: 'VALIDATE-BS',
    SEARCHITEM: 'VALIDATE-SEARCHITEM',
    PURCHASEPRICEHISTORY: 'VALIDATE-PURCHASEPRICEHISTORY',
    PURCHASEDELIVERYPRICE_SA: 'VALIDATE-PURCHASEDELIVERYPRICE_SA',
    PURCHASEDELIVERY_SA: 'VALIDATE-PURCHASEDELIVERY_SA',
    PURCHASEORDER_SA: 'VALIDATE-PURCHASEORDER_SA',
    PURCHASEQUOTATION_SA: 'VALIDATE-PURCHASEQUOTATION_SA',
    PURCHASEINVOICE_SA: 'VALIDATE-PURCHASEINVOICE_SA',
    PURCHASEASSET_SA: 'VALIDATE-PURCHASEASSET_SA',
    PURCHASEFINALORDER_SA: 'VALIDATE-PURCHASEFINALORDER_SA',
    SALESORDER_SA: 'VALIDATE-SALESORDER_SA',
    SALESFINALORDER_SA: 'VALIDATE-SALESFINALORDER_SA',
    SALESDELIVERY_SA: 'VALIDATE-SALESDELIVERY_SA',
    SALESINVOICE_SA: 'VALIDATE-SALESINVOICE_SA',
    SALESINVOICEASSET_SA: 'VALIDATE-SALESINVOICEASSET_SA',
    SALESASSET_SA: 'VALIDATE-SALESASSET_SA',
    SALESQUOTATION_SA: 'VALIDATE-SALESQUOTATION_SA',
    TREASURY: 'VALIDATE-TREASURY',
    DOCUMENTCONTROL: 'VALIDATE-DOCUMENTCONTROL',
    INVENTORY: 'VALIDATE-INVENTORY',
    BALANCED_LINE: 'VALIDATE-BALANCED_LINE',
    EMPLOYEE: 'VALIDATE-EMPLOYEE',
    SESSION: 'VALIDATE-SESSION',
    TRANSFERORDER: 'VALIDATE-TRANSFERORDER',
    CNSSDECLARATION: 'VALIDATE-CNSSDECLARATION'
  };
  public static SALES_DELIVER = 'SALES_DELIVER';
  public static AccountingPermissions = {
    ACCOUNTING_SETTINGS: 'ACCOUNTING_SETTINGS',
    ACCOUNTING: 'ACCOUNTING',

    DOCUMENTS_ACCOUNTS: 'DOCUMENTS_ACCOUNTS',
    ADD_DOCUMENTS_ACCOUNTS: 'ADD_DOCUMENTS_ACCOUNTS',
    VIEW_DOCUMENTS_ACCOUNTS: 'VIEW_DOCUMENTS_ACCOUNTS',
    UPDATE_DOCUMENTS_ACCOUNTS: 'UPDATE_DOCUMENTS_ACCOUNTS',
    ADD_FILE_ATTACHMENT_TO_DOCUMENTS_ACCOUNTS: 'ADD_FILE_ATTACHMENT_TO_DOCUMENTS_ACCOUNTS',
    DELETE_FILE_ATTACHMENT_TO_DOCUMENTS_ACCOUNTS: 'DELETE_FILE_ATTACHMENT_TO_DOCUMENTS_ACCOUNTS',
    DELETE_DOCUMENTS_ACCOUNTS: 'DELETE_DOCUMENTS_ACCOUNTS',
    IMPORT_DOCUMENTS_ACCOUNTS: 'IMPORT_DOCUMENTS_ACCOUNTS',
    EXPORT_DOCUMENTS_ACCOUNTS: 'EXPORT_DOCUMENTS_ACCOUNTS',
    EXPORT_MODEL_DOCUMENTS_ACCOUNTS: 'EXPORT_MODEL_DOCUMENTS_ACCOUNTS',

    ACCOUNTING_LETTERING: 'ACCOUNTING_LETTERING',
    VIEW_ACCOUNTING_LETTERING: 'VIEW_ACCOUNTING_LETTERING',
    PERFORM_LETTERING: 'PERFORM_LETTERING',
    PERFORM_DELETTERING: 'PERFORM_DELETTERING',

    RECONCILIATION_BANK: 'RECONCILIATION_BANK',
    VIEW_RECONCILIATION_BANK: 'VIEW_RECONCILIATION_BANK',
    PRINT_RECONCILIATION_BANK: 'PRINT_RECONCILIATION_BANK',
    RECONCILE_ENTRY: 'RECONCILE_ENTRY',
    UNRECONCILE_ENTRY: 'UNRECONCILE_ENTRY',
    VIEW_RECONCILIATION_BANK_STATEMENT: 'VIEW_RECONCILIATION_BANK_STATEMENT',
    PRINT_RECONCILIATION_BANK_STATEMENT: 'PRINT_RECONCILIATION_BANK_STATEMENT',

    AMORTIZATION_OF_IMMOBILIZATIONS: 'AMORTIZATION_OF_IMMOBILIZATIONS',
    PRINT_AMORTIZATION_TABLE: 'PRINT_AMORTIZATION_TABLE',
    GENERATE_DOCUMENT_FROM_ACTIVES: 'GENERATE_DOCUMENT_FROM_ACTIVES',

    IMPORT_ACCOUNTING_DOCUMENTS: 'IMPORT_ACCOUNTING_DOCUMENTS',
    GENERATE_DOCUMENT_ACCOUNT_FROM_DOCUMENT: 'GENERATE_DOCUMENT_ACCOUNT_FROM_DOCUMENT',

    EDITIONS_REPORTS: 'EDITIONS_REPORTS',
    VIEW_EDITIONS_REPORTS: 'VIEW_EDITIONS_REPORTS',
    PRINT_EDITIONS_REPORTS: 'PRINT_EDITIONS_REPORTS',

    FINANCIAL_STATES_REPORTS: 'FINANCIAL_STATES_REPORTS',
    VIEW_FINANCIAL_STATES_REPORTS: 'VIEW_FINANCIAL_STATES_REPORTS',
    PRINT_FINANCIAL_STATES_REPORTS: 'PRINT_FINANCIAL_STATES_REPORTS',
    UPDATE_FINANCIAL_STATES_REPORTS_FORMULA: 'UPDATE_FINANCIAL_STATES_REPORTS_FORMULA',

    JOURNALS_REPORTS: 'JOURNALS_REPORTS',
    VIEW_JOURNALS_REPORTS: 'VIEW_JOURNALS_REPORTS',
    PRINT_JOURNALS_REPORTS: 'PRINT_JOURNALS_REPORTS',

    CHART_OF_ACCOUNTS: 'CHART_OF_ACCOUNTS',
    ADD_CHART_OF_ACCOUNTS: 'ADD_CHART_OF_ACCOUNTS',
    VIEW_CHART_OF_ACCOUNTS: 'VIEW_CHART_OF_ACCOUNTS',
    UPDATE_CHART_OF_ACCOUNTS: 'UPDATE_CHART_OF_ACCOUNTS',
    DELETE_CHART_OF_ACCOUNTS: 'DELETE_CHART_OF_ACCOUNTS',
    IMPORT_CHART_OF_ACCOUNTS: 'IMPORT_CHART_OF_ACCOUNTS',
    EXPORT_CHART_OF_ACCOUNTS: 'EXPORT_CHART_OF_ACCOUNTS',
    EXPORT_MODEL_CHART_OF_ACCOUNTS: 'EXPORT_MODEL_CHART_OF_ACCOUNTS',

    JOURNALS: 'JOURNALS',
    ADD_JOURNALS: 'ADD_JOURNALS',
    VIEW_JOURNALS: 'VIEW_JOURNALS',
    UPDATE_JOURNALS: 'UPDATE_JOURNALS',
    DELETE_JOURNALS: 'DELETE_JOURNALS',
    IMPORT_JOURNALS: 'IMPORT_JOURNALS',
    EXPORT_JOURNALS: 'EXPORT_JOURNALS',
    EXPORT_MODEL_JOURNALS: 'EXPORT_MODEL_JOURNALS',

    ACCOUNTING_ACCOUNTS: 'ACCOUNTING_ACCOUNTS',
    ADD_ACCOUNTING_ACCOUNTS: 'ADD_ACCOUNTING_ACCOUNTS',
    VIEW_ACCOUNTING_ACCOUNTS: 'VIEW_ACCOUNTING_ACCOUNTS',
    UPDATE_ACCOUNTING_ACCOUNTS: 'UPDATE_ACCOUNTING_ACCOUNTS',
    DELETE_ACCOUNTING_ACCOUNTS: 'DELETE_ACCOUNTING_ACCOUNTS',
    IMPORT_ACCOUNTING_ACCOUNTS: 'IMPORT_ACCOUNTING_ACCOUNTS',
    EXPORT_ACCOUNTING_ACCOUNTS: 'EXPORT_ACCOUNTING_ACCOUNTS',
    EXPORT_MODEL_ACCOUNTING_ACCOUNTS: 'EXPORT_MODEL_ACCOUNTING_ACCOUNTS',

    ACCOUNTING_TEMPLATE: 'ACCOUNTING_TEMPLATE',
    ADD_ACCOUNTING_TEMPLATE: 'ADD_ACCOUNTING_TEMPLATE',
    VIEW_ACCOUNTING_TEMPLATE: 'VIEW_ACCOUNTING_TEMPLATE',
    UPDATE_ACCOUNTING_TEMPLATE: 'UPDATE_ACCOUNTING_TEMPLATE',
    DELETE_ACCOUNTING_TEMPLATE: 'DELETE_ACCOUNTING_TEMPLATE',
    IMPORT_ACCOUNTING_TEMPLATE: 'IMPORT_ACCOUNTING_TEMPLATE',
    EXPORT_ACCOUNTING_TEMPLATE: 'EXPORT_ACCOUNTING_TEMPLATE',
    EXPORT_MODEL_ACCOUNTING_TEMPLATE: 'EXPORT_MODEL_ACCOUNTING_TEMPLATE',

    FISCAL_YEARS: 'FISCAL_YEARS',
    ADD_FISCAL_YEARS: 'ADD_FISCAL_YEARS',
    VIEW_FISCAL_YEARS: 'VIEW_FISCAL_YEARS',
    UPDATE_FISCAL_YEARS: 'UPDATE_FISCAL_YEARS',
    CLOSE_FISCAL_YEARS: 'CLOSE_FISCAL_YEARS',
    OPEN_FISCAL_YEARS: 'OPEN_FISCAL_YEARS',
    CONCLUDE_FISCAL_YEARS: 'CONCLUDE_FISCAL_YEARS',

    AMORTIZATION_OF_IMMOBILIZATIONS_SETTINGS: 'AMORTIZATION_OF_IMMOBILIZATIONS_SETTINGS',
    VIEW_AMORTIZATION_OF_IMMOBILIZATIONS_SETTINGS: 'VIEW_AMORTIZATION_OF_IMMOBILIZATIONS_SETTINGS',
    UPDATE_AMORTIZATION_OF_IMMOBILIZATIONS_SETTINGS: 'UPDATE_AMORTIZATION_OF_IMMOBILIZATIONS_SETTINGS',

    ACCOUNTING_STANDARD_REPORTS: 'ACCOUNTING_STANDARD_REPORTS',
    VIEW_ACCOUNTING_STANDARD_REPORTS: 'VIEW_ACCOUNTING_STANDARD_REPORTS',
    UPDATE_ACCOUNTING_STANDARD_REPORTS_FORMULA: 'UPDATE_ACCOUNTING_STANDARD_REPORTS_FORMULA',

    FINANCIAL_ACCOUNTS_SETTINGS: 'FINANCIAL_ACCOUNTS_SETTINGS',
    VIEW_FINANCIAL_ACCOUNTS_SETTINGS: 'VIEW__FINANCIAL_ACCOUNTS_SETTINGS',
    UPDATE_FINANCIAL_ACCOUNTS_SETTINGS: 'UPDATE_FINANCIAL_ACCOUNTS_SETTINGS',

    TIERS_ACCOUNTS_SETTINGS: 'TIERS_ACCOUNTS_SETTINGS',
    VIEW_TIERS_ACCOUNTS_SETTINGS: 'VIEW_TIERS_ACCOUNTS_SETTINGS',
    UPDATE_TIERS_ACCOUNTS_SETTINGS: 'UPDATE_TIERS_ACCOUNTS_SETTINGS',

    PAYMENTS_ACCOUNTS_SETTINGS: 'PAYMENTS_ACCOUNTS_SETTINGS',
    VIEW_PAYMENTS_ACCOUNTS_SETTINGS: 'VIEW_PAYMENTS_ACCOUNTS_SETTINGS',
    UPDATE_PAYMENTS_ACCOUNTS_SETTINGS: 'UPDATE_PAYMENTS_ACCOUNTS_SETTINGS',

    AMORTIZATION_ACCOUNT_SETTINGS: 'AMORTIZATION_ACCOUNT_SETTINGS',
    VIEW_AMORTIZATION_ACCOUNT_SETTINGS: 'VIEW_AMORTIZATION_ACCOUNT_SETTINGS',
    UPDATE_AMORTIZATION_ACCOUNT_SETTINGS: 'UPDATE_AMORTIZATION_ACCOUNT_SETTINGS',

    ACCOUNTING_JOURNAL_SETTINGS : 'ACCOUNTING_JOURNAL_SETTINGS',
    VIEW_ACCOUNTING_JOURNAL_SETTINGS: 'VIEW_ACCOUNTING_JOURNAL_SETTINGS',
    UPDATE_ACCOUNTING_JOURNAL_SETTINGS: 'UPDATE_ACCOUNTING_JOURNAL_SETTINGS',

    USER_ACCOUNTING_SETTINGS: 'USER_ACCOUNTING_SETTINGS',
    VIEW_USER_ACCOUNTING_SETTINGS: 'VIEW_USER_ACCOUNTING_SETTINGS',
    UPDATE_USER_ACCOUNTING_SETTINGS: 'UPDATE_USER_ACCOUNTING_SETTINGS'
  };

}

