export enum ActionFilterTypeEnum {
  ACTION_UPCOMING = 0,
  ACTION_PREVIOUS = 1,
  ACTION_BY_STATE = 2,
  ACTION_ASSIGNED_TO = 3,
  ACTION_BY_ORGANIZATION = 4,
  ACTION_BY_CONTACT = 5,
  ACTION_BY_TYPE = 6,
  ACTION_ALL = 7,
  ACTION_MY_ACTIONS = 8,
  ACTION_BY_COMMERCIAL = 9,
  ACTION_BY_PRIORITY = 10
}
