export enum PermissionType {
  ALL_PERMSSION = 'ALL',
  OWNER_PERMSSION = 'OWNER',
  TEAM_PERMSSION = 'TEAM',
  INDIVIDUAL_PERMSSION = 'INDIVIDUAL',
  NOT_ALLOWED_TO_UPDATE = 'NOT_ALLOWED_TO_UPDATE',
}
