export enum PriceTypeEnumerator {
    PURCHASED_QUANTITY = "PURCHASED_QUANTITY",
    TOTAL_PURCHASES = "TOTAL_PURCHASES",
    COLLAPSE_SPECIAL_PRICE_DISCOUNT_TITLE = "COLLAPSE_SPECIAL_PRICE_DISCOUNT_TITLE",
    COLLAPSE_GIFTED_ITEMS_DISCOUNT_TITLE = "COLLAPSE_GIFTED_ITEMS_DISCOUNT_TITLE"
  }